[package]
name = "lyly-os"
version = "0.1.0"
edition = "2021"

[dependencies]
stivale-boot = "0.2.6"

[[bin]]
name = "lyly-os"
path = "src/main.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"